### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by ddeboer** [cultuurnet/Entry#2]
What is the status of this project? We’re currently building UiT entry API integration into a PHP app and we’ve found multiple libraries that seem to do more or less the same:

* Entry
* udb3-php
* culturefeed-php

What is the current recommendation for production apps? Provisionally we decided in favour of Entry, as  udb3-php has way too many dependencies (in my opinion) and culturefeed-php seems rather outdated.

**Comment by cyberwolf** [comment]
Hi David,

The Entry library is a (currently limited) rework of the entry part of culturefeed-php (https://github.com/cultuurnet/culturefeed-php/tree/master/CultureFeed/CultureFeed/EntryApi), based on [Auth ](https://github.com/cultuurnet/auth) and using Guzzle (although still version 3, still a huge improvement over the custom HTTP client library of culturefeed-php). If you need all features immediately, I advise you to stick to culturefeed-php for now.

**Comment by ddeboer** [comment]
Kristof, thanks for the explanation. As I prefer a standard HTTP client over custom ones, I decided to use the newer Entry for now, with some changes (#1).
